export default {
	cupcake: [
		{
			id: 12400901,
			name: 'Chocolate Peanut Butter',
			price: '5',
			img: 'chocholate_peanutbutter_cupcake.png',
			description:
				'If you wish for the taste of pure chocolaty delicacy, this cake could be an idea deal for you. Coming with chocolate base and swirls of chocolate cream and sprinkled chocolate chips, this cake makes you chocolate dream comes true.',
			sku: 401,
			calo: 250,
			serving_size: '75g',
			total_fat: 15,
			protein: 2.5,
		},
		{
			id: 12400902,
			name: 'Chocolate Raspberry',
			price: '4',
			img: 'chocholate_raspberry_decadence_cupcake.png',
			description:
				"'Wow' is the only word that naturally comes out of your mouth after seeing this cute sugary delight. Coming with chocolate cup cake base, whipped vanilla cream, chocolate sauce and the sprinkles of edible sugar candies.",
			sku: 402,
			calo: 270,
			serving_size: '80g',
			total_fat: 15,
			protein: 2.7,
		},
		{
			id: 12400903,
			name: 'Salted Caramel',
			price: '5',
			img: 'calted_caramel_decadence_cupcake.png',
			description:
				"Here's your perfect morning partner. Wake up fresh and experience the coffee rush in your veins as you take a bite of these cupcakes--baked with a coffee sponge frosted with a buttercream swirl, topped with chocolate ball and dusted with coffee powder.",
			sku: 403,
			calo: 240,
			serving_size: '75g',
			total_fat: 14,
			protein: 2.5,
		},
		{
			id: 12400904,
			name: 'Carrot Cake',
			price: '4',
			img: 'carrot_cake_cupcake.png',
			description:
				'The goodness of this sweet and enticing fruit can now be enjoyed in a cupcake. The sponge cupcake base is siwrled with whipped vanilla icing with mango flavoured glazed. Relish the sweetness of carrots and deliciousness of cake in every bite.',
			sku: 404,
			calo: 260,
			serving_size: '75g',
			total_fat: 13,
			protein: 2.5,
		},
		{
			id: 12400905,
			name: 'Lemon Crunch',
			price: '6',
			img: 'lemon_crunch_cupcake.png',
			description:
				'When a delicious cup cake base and lemon perfectly make the heaven blend, makes this outstanding cup cake. The best fact about this cake is that it looks simple, decent but tastes like heaven.',
			sku: 405,
			calo: 260,
			serving_size: '75g',
			total_fat: 12,
			protein: 2.2,
		},

		{
			id: 12400906,
			name: 'Pistachio',
			price: '4',
			img: 'pistachio_cupcake.png',
			description:
				'Celebrate your pride of belonging to a nation so rich and strong. This cupcakes with a mushy chocolate base and swirls of heavily whipped cream is here to celebrate the sweetness of being an Indian. With a fondant flag hoisted, these cupcakes would definitely leave you spellbound.',
			sku: 406,
			calo: 280,
			serving_size: '85g',
			total_fat: 18,
			protein: 3.0,
		},
	],
	drink: [
		{
			id: 24198901,
			name: 'Coca',
			price: '1',
			img: 'coca.png',
			description:
				'Enjoy Coca-Cola’s crisp, delicious taste with meals, on the go, or to share. ',
			sku: 501,
			calo: 105,
			serving_size: '250ml',
			total_fat: 0,
			protein: 0,
		},
		{
			id: 24198902,
			name: 'Pepsi',
			price: '1',
			img: 'pepsi.png',
			description: 'Pepsi - the bold, refreshing, robust cola',
			sku: 502,
			calo: 95,
			serving_size: '250ml',
			total_fat: 0,
			protein: 0,
		},
		{
			id: 24198903,
			name: 'Lemonade',
			price: '2',
			img: 'Lemonade.jpg',
			description:
				'Simple and easy method for perfect lemonade every time! ',
			sku: 503,
			calo: 50,
			serving_size: '500ml',
			total_fat: 0,
			protein: 0,
		},
		{
			id: 24198904,
			name: 'Boba tea',
			price: '3',
			img: 'bubble-tea.jpeg',
			description:
				'Black tea is shaken with frothy milk, crushed ice, and a few generous handfuls of marble-sized, caramelized tapioca pearls.  ',
			sku: 504,
			calo: 200,
			serving_size: '250ml',
			total_fat: 18,
			protein: 3.0,
		},
	],
	burger: [
		{
			id: 300198901,
			name: 'Cheeseburger',
			price: '5',
			img: 'burger1.jpg',
			description:
				'Our simple, classic cheeseburger begins with a 100% pure beef burger seasoned with just a pinch of salt and pepper. The Cheeseburger is topped with a tangy pickle, chopped onions, ketchup, mustard, and a slice of melty American cheese. It contains no artificial flavors, preservatives or added colors from artificial sources.',
			sku: 601,
			calo: 266,
			serving_size: '100g',
			total_fat: 10.1,
			protein: 13.3,
		},
		{
			id: 300198902,
			name: 'Double Quarter Pounder',
			price: '7',
			img: 'burger2.jpg',
			description:
				'Each Double Quarter Pounder with Cheese features two quarter pound 100% fresh beef burger patties that are hot, deliciously juicy and cooked when you order. beef patties are seasoned with just a pinch of salt and pepper, sizzled on a flat iron grill, then topped with slivered onions, tangy pickles and two slices of melty cheese on a sesame seed bun. It contains no artificial flavors, preservatives or added colors from artificial sources.',
			sku: 602,
			calo: 300,
			serving_size: '120g',
			total_fat: 12.1,
			protein: 14.3,
		},
		{
			id: 300198903,
			name: 'Quarter Pounder Cheese Bacon',
			price: '7.5',
			img: 'burger3.jpg',
			description:
				"Each Quarter Pounder with Cheese Bacon burger features thick-cut applewood smoked bacon atop a ¼ lb.* of 100%  fresh beef that's cooked when you order. It's a hot, deliciously juicy bacon cheeseburger, seasoned with just a pinch of salt and pepper and sizzled on our flat iron grill. Layered with two slices of melty American cheese, slivered onions and tangy pickles on a soft, fluffy sesame seed hamburger bun.",
			sku: 603,
			calo: 210,
			serving_size: '110g',
			total_fat: 11.1,
			protein: 13.3,
		},
		{
			id: 300198904,
			name: 'Quarter Pounder with Cheese',
			price: '8',
			img: 'burger4.jpg',
			description:
				'Quarter Pounder with Cheese Deluxe is a fresh take on a Quarter Pounder classic burger. Crisp shredded lettuce and three Roma tomato slices top a ¼ lb.* of 100% fresh beef that’s hot, deliciously juicy and cooked when you order. Seasoned with just a pinch of salt and pepper and sizzled on our flat iron grill. Layered with two slices of melty American cheese, creamy mayo, slivered onions and tangy pickles on a soft, fluffy sesame seed hamburger bun.',
			sku: 604,
			calo: 200,
			serving_size: '100g',
			total_fat: 9.1,
			protein: 11.3,
		},
		{
			id: 300198905,
			name: 'Double Cheeseburger',
			price: '4',
			img: 'burger5.jpg',
			description:
				'Our simple, classic cheeseburger begins with a 100% pure beef burger seasoned with just a pinch of salt and pepper. The Cheeseburger is topped with a tangy pickle, chopped onions, ketchup, mustard, and a slice of melty American cheese. It contains no artificial flavors, preservatives or added colors from artificial sources.',
			sku: 605,
			calo: 250,
			serving_size: '100g',
			total_fat: 13.1,
			protein: 13.3,
		},
	],
	sandwich: [
		{
			id: 4092451,
			name: 'Black Angus',
			price: '5',
			img: 'sandwich1.jpg',
			description:
				'Black Angus roast beef, bacon, sharp cheddar, Swiss, red onion, spring mix, tomato, horseradish sauce and mayo on wheat.',
			sku: 701,
			calo: 220,
			serving_size: '132g',
			total_fat: 7.3,
			protein: 8.2,
		},
		{
			id: 4092452,
			name: 'Orange Cranberry',
			price: '6',
			img: 'sandwich2.jpg',
			description:
				"The SE's Club with Orange Cranberry Sauce in place of honey mustard.",
			sku: 702,
			calo: 200,
			serving_size: '102g',
			total_fat: 9.3,
			protein: 10.2,
		},
		{
			id: 4092453,
			name: 'Alister Turkey',
			price: '5.5',
			img: 'sandwich3.jpg',
			description:
				"Smoked turkey, Black Forest ham, bacon, sharp cheddar, Swiss, spring mix, tomato, mayo and SE's Honey Mustard on wheat.",
			sku: 703,
			calo: 200,
			serving_size: '112g',
			total_fat: 12.3,
			protein: 15.2,
		},
		{
			id: 4092454,
			name: 'King Club',
			price: '7',
			img: 'sandwich4.jpg',
			description: "Twice the ingredients of SE's Club on country white",
			sku: 704,
			calo: 230,
			serving_size: '142g',
			total_fat: 8.3,
			protein: 10.2,
		},
		{
			id: 4092455,
			name: 'Grilled Chicken',
			price: '4',
			img: 'sandwich5.jpg',
			description:
				"SE's Club with grilled chicken in place of ham and turkey.",
			sku: 705,
			calo: 230,
			serving_size: '122g',
			total_fat: 5.3,
			protein: 10.2,
		},
	],
};